# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#解决报[Xcodeproj] Generated duplicate UUIDs:
install! 'cocoapods', :deterministic_uuids => false
#use_frameworks!
# 官方
source 'https://github.com/CocoaPods/Specs.git'

target 'TestPlayer' do
  
  # demo需要
  pod 'SDWebImage'
  pod 'YYKit'
  pod 'Masonry', '~> 1.1.0'
  
  # 导入
 pod 'HZAVPlayer', :path => './'#导入方式
 pod 'GCDWebServer', '~> 3.5.4' 
  
end
